### ISSUE TITLE
Does this code is similar with the BERT ,or what's the difference? thx.

### ISSUE THREAD

**Issue by binwang672012** [ivan-bilan/tac-self-attention#4]

**Comment by ivan-bilan** [comment]
This project uses the encoder part of the Transformer architecture (you can learn more about the Transformer architecture at https://jalammar.github.io/illustrated-transformer/), but a modified version that takes care of Positional Embeddings in a different way. Additionally, in order for it to work on the task of Relation Extraction there is another custom attention layer used on top of the Transformer encoder. BERT also uses a stack of Transformer encoders (24 to be precise), you could say BERT is an architecture that consists mostly of the same logic that Transformer does.

**Comment by binwang672012** [comment]
> This project uses the encoder part of the Transformer architecture (you can learn more about the Transformer architecture at https://jalammar.github.io/illustrated-transformer/), but a modified version that takes care of Positional Embeddings in a different way. Additionally, in order for it to work on the task of Relation Extraction there is another custom attention layer used on top of the Transformer encoder. BERT also uses a stack of Transformer encoders (24 to be precise), you could say BERT is an architecture that consists mostly of the same logic that Transformer does.

thank you for your explanation about my puzzle, I feel more clearly about this code .And I also had read your article "The Illustrated Transformer" ,that is clearly expressed to understand , I like it very much ! I'm looking forward to your article ,Thank you!  👍
